botCommands/help.js
Currently, the help command is triggered in texts which contain the substring `'/help'`. The PR fixes it by strictly looking for `/help`.
@codyloyd This is really minor. Should we also make it case-sensitive and ignore whitespaces at the beginning and at the end? What do you think?
=> Make help regex strict

botCommands/partyParrot.js
Making the discord a party.
I noticed some of the non-HD partyparrot links were being phased out, resulting in broken links and empty commands. Non-HD links were replaced with their HD counterparts, or removed entirely.
I also added odin-parrot and angry-parrot commands.
partyparrot
=> Less sharks, more parrots

Procfile
Because:
* To host the bot on heroku we need to provide a procfile which tells heroku what process it should run the bot on.
=> Chore: Add Procfile for Heroku

botCommands/points.js
Because:
* at the moment we are getting back all the points data from the api when we don't need to.
This Commit:
* Passes the start position(offset) and the length(limit) of points records we want.
=> Chore: Pass Limit and Offset to Points API

botCommands/help.js
Makes the `/help` command a bit smarter by using a different regex.
The previous `\b` at the end matched periods so `http://help.domain.com` would be matched.
New regex requires that `/help` command is at the end of the input, which I do not see to be an issue.
=> use smarter regex for help command

botCommands/__snapshots__/shrug.test.js.snap, botCommands/__snapshots__/simpleCommands.test.js.snap, botCommands/__snapshots__/time.test.js.snap, botCommands/mockData.js, botCommands/partyParrot.js, botCommands/shrug.js, botCommands/shrug.test.js, botCommands/simpleCommands.js, botCommands/simpleCommands.test.js, botCommands/time.test.js, botEngine.js
- Created snapshots + tests for the `shrug.js`, `simpleCommands.js`, and `time.js` files. 
- The snapshots for shrug are a bit wonky, but I think it's due to escaping characters. I checked the output being returned with a console.log, and it doesn't look the same as the output being returned in the snapshots, even if it does match up properly when run through the bot and manually checked. I'll likely need some review here.
- Additionally, I had to make a few lines dedicated to checking that all of the permutations of the word "shrug" would trigger the regex. I wasn't sure if I needed to do the same in other areas, and am looking to discuss how to improve this piece. checking each one would result in thousands of tests for this one file, so I am not sure if that was necessary if we already …
=> shrug, simpleCommands, and time tests

botCommands/__snapshots__/windows.test.js.snap, botCommands/windows.js, botCommands/windows.test.js
- add windows command affirming our recommendations in the curriculum
- NOTE: The pre-push hook was bypassed using `--no-verify` due to other commands failing the regex portion.
=> add windows command

botCommands/__snapshots__/points.test.js.snap, botCommands/points.js, botCommands/points.test.js
This PR solves this issue: 
- points.js commands regexes need to pass their tests https://github.com/TheOdinProject/odin-bot-v2/issues/92
After discussing it with Tatiana, I changed @user and @odin-bot to <@!1233456679> in the test file to align it with Discord's syntax for mentions and corrected some minor errors. That's also why the snapshots have changed. 
Other than that, I just adjusted the regexes to make them pass the tests. 
I think my Prettier replaced the double quotes by single quotes and removed unnecessary semi-colons and whitespace... Hope that's ok.
=> Fix regexes and adjust tests for correct Discord mentions syntax

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/COMMAND_REQUEST.md, .github/PULL_REQUEST_TEMPLATE.md
Adds a `.github` directory that includes Issues and PR templates, and closes #102.
=> add issue and PR templates for the odin bot

botCommands/__snapshots__/debug.test.js.snap, botCommands/debug.js, botCommands/debug.test.js
Extended `/debug` command to accept `js` and `rb` arguments and give out appropriate debugging articles.
#105
=> Extend /debug command to add "JS" and "Ruby" commands.

botCommands/__snapshots__/points.test.js.snap, botCommands/points.js, botCommands/points.test.js
The regex now uses a `RegExp()` constructor that allows us to break the complex regex into distinct pieces, such as the Discord username, and our incrementing matchers like the star and ++. The star matcher now works correctly once more. 
A bug was found in the tests due to the behavior of `RegExp.test()` and `lastIndex`, so the tests now use `String.match()` so we can get an accurate result. The tests now also include cases for our star matcher. 
NOTE:  I had to push using --no-verify due to ESLint issues, but will fix the repository and make a separate PR so our master branch will now be ESLint compliant and contributors will not be met with unrelated issues when attempting to push their changes.
Closes #107
=> Fix addPoints command regex

botCommands/__snapshots__/windows.test.js.snap
Because:
* A snapshot was outdated.
=> Fix: Failing Windows Spec.

botEngine.js
Our Discord community now uses the membership screening feature built-in to Discord, removing the need for odin-bot to respond to user messages in the "I-didnt-read-the-rules" channel.
This commit:
- Removes the associated code for the channel message listener.
=> chore: remove #i-didnt-read-the-rules msg listener

botCommands/__snapshots__/faq.test.js.snap, botCommands/faq.js
Changed the `/faq` embed to use URL of #faq channel instead of Channel Id.
**Reason:** The `#faq` link was not clickable in Android Phones.
No
=> Fix /faq to use URL

botEngine.js
Because:
The odin-bot would delete messages immediately upon sending from commands unrelated to the welcome message in #introductions.
This commit:
Prevents the odin-bot from deleting messages that are not the welcome message (as intended).
Updates bot to not send a welcome message if someone with administrative privileges of any kind sends a message.
=> fix(messages): prevent bot from deleting non-welcome message

.circleci/config.yml
This commit:
- Updates node orb version to the most recent, 5.0.0
=> update circleci node orb to  5.0.0

.eslintrc.json, botCommands/__snapshots__/debug.test.js.snap, botCommands/__snapshots__/faq.test.js.snap, botCommands/__snapshots__/help.test.js.snap, botCommands/__snapshots__/simpleCommands.test.js.snap, botCommands/__snapshots__/windows.test.js.snap, botCommands/debug.js, botCommands/faq.js, botCommands/help.js, botCommands/mockData.test.js, botCommands/points.js, botCommands/points.test.js, botCommands/simpleCommands.js, botCommands/time.js, botCommands/windows.js, botEngine.js, index.js, package-lock.json, package.json
This commit:
- Upgrades `discord.js` from v12 to v13
- Upgrades `jest` to the latest version to support Node 16
- Upgrades commands containing embeds to use the v13 api semantics for `discord.js`
- Updates various array construction and fetching of guild members due to v13 changes
- Updates relevant tests and snapshots, if needed
=> chore: upgrade bot to use discord.js v13

index.js
Problem:
The `/leaderboard` command was returning a leaderboard that was missing members that exist in our points table in the database. This is due to us fetching members from the cache (which is not always reliable or up to date).
This commit:
- Adds the GUILD_MEMBERS intent such that the bot can fetch members (as it is required to listen to certain events as well, such as a member joining or leaving)
- Fetches all members of the discord on startup, such that the cache for the current bot session is up to date.
=> fix: fetch members on startup for cache integrity

.env.sample, index.js
This commit:
- Refactors the usage of the Discord Guild ID to use an environment variable.
- Updates the `.env.sample` such that there's visibility on the requirement of this key.
=> add discord guild id to env var

botEngine.js
Reason: was broken probably because of API changes from discord.js v12
<hr>
Nobot broken
Hopefully fixes nobot
n/a
=> Fix nobot check in message listener

services/bookmark-message.service.js
<hr>
Related to #242 
Remove bookmark embed
n/a
=> Chore: update bookmark message sent to bot-spam-playground channel

botCommands/__snapshots__/points.test.js.snap, botCommands/points.js, botCommands/points.test.js
Normal users seemed to be able to grant a user more than one point by referencing them more than once in a message.
* Adds a check in `getUserIdsFromMessage` to prevent duplicates
* Adds tests for the scenario where a user is mentioned twice in a message.
* Update other tests to use unique user IDs
* Update snapshots to accommodate test changes
Closes #257 
-   [x] The `This PR` section has a bullet point list describing the …
=> feat: disallow adding multiple points

new-era-commands/slash/chooseyourpath.js
- While default emoij's can be embedded by simply using `:name:` in a string, this does not work for server specific emoij's, which instead require the `<:name:id>` format. Currently the ruby and node emoij's are using the standard way instead of the server specific way, causing `:node:` and `:ruby:` to show up instead of the intended emoij's
- Changes the way the path emoijs are specified to the right formatting, which causes them to actually display the intended emoij
-   [x] The `Because` …
=> chooseyourpath: fix custom emoij handling

botCommands/points.js
- It is nice to mark certain significant milestones (1K and 4K) in gained points
- Adds two new possible exclamations, one for 1000 points and one for 4000 points
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, …
=> Points.js: Add two more possible exclamations for certain milestones

bin/deploy-commands.js
- the comments in the deploy file mention running `node bin/deploy.js`, but the file is no longer called that
- corrects the comment to `node bin/deploy-commands.js`
=> Deploy command: update deploy filename

botCommands/__snapshots__/help.test.js.snap, botCommands/help.js, new-era-commands/slash/help.js
The links in the commands are outdated and lead to a 404 page
- update the links
Closes #XXXXX
-   [ ] If applicable, I have ensured all tests related to any command files included in this …
=> bot help command: update community guide links for the help command

botCommands/bootcamps.js, botCommands/bootcamps.test.js
- `!bootcamp` is a reasonable alternative to `!bootcamps`, and often gets used when people want `!bootcamp`
- Modifies the regex to make `!bootcamp` work, and update associated jest tests …
=> Bootcamps: make !bootcamp also work

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
- We are centralizing to https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md as the single source of truth for CONTRIBUTING.md
- Changes all https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md links to https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md
Part of TheOdinProject/theodinproject#3901
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Intro to HTML and CSS lesson: Fix link text`
-   [x] The `This PR` section has a bullet point list describing the …
=> Chore:  repoint contributing links to .github/CONTRIBUTING.md 

botCommands/__snapshots__/bootcamps.test.js.snap, botCommands/bootcamps.js
- Twitter is becoming increasingly hostile to non-logged in users and seems to be degrading in general, leading to issues with accessing the bootcamp tweet
- Changes it to a Web Archive version, as linked on Discord (https://discord.com/channels/505093832157691914/707225752608964628/1125631263953387540)
-   [x] If applicable, I have ensured all …
=> Bootcamps: change link to Web Archive

botCommands/__snapshots__/question-legacy.test.js.snap, botCommands/__snapshots__/simpleCommands.test.js.snap, botCommands/question-legacy.js, botCommands/question-legacy.test.js, botCommands/simpleCommands.js, botCommands/simpleCommands.test.js
We are slowly but surely updating our commands to slash commands and I'm doing some bot housekeeping. The `!question` command was decided on in the past as a great one to keep in the legacy format as well. It works nicely when typed in a sentence like:
> Hi there! I really think people would be way better equipped to help you out if you format your `!question` according to the below bot output. 
- moves the `!question` command out of the `simpleCommands` file into their own `question-legacy` file
- adds a separate test file for the `!question` command and removes the test from the `simpleCommands.test.js`
- adds a separate snapshot file for the `!question` cb and removes it from the `simpleCommands` snapshot file.
Closes #XXXXX
-   [x] I have thoroughly read and understand [The Odin …
=> move legacy !question command to its own module

new-era-commands/slash/searchtop.js
- Google has added an embed to the search links, which adds nothing but takes up a large amount of chat space
- suppresses the embed from the link
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
=> /searchtop: suppres google embed

botCommands/club_40_gifs.json
This [gif](https://media.tenor.com/VRYCq0ZeasQAAAAC/dundie-award.gif) that does not seem to have an author pop up in Club-40 and it is not in [collection of possible gifs](https://github.com/TheOdinProject/odin-bot-v2/blob/main/botCommands/club_40_gifs.json).
- Added one club-40 .gif  
Closes #408
-   [x] If this PR addresses an open issue, it is …
=> Add a new club-40 gif

new-era-commands/slash/memory.js
This PR adds a slash-command to the odin-bot to provide a link to Carlos' blog post on memorization, and allows users to refer question-askers seeking advice on whether to memorize the learning material.
- Adds slash-command to new-era-commands directory (compare original PR linked below)
- Changes callback from prior PR to use embed format.
- Changes link to "meaningful text" to better adhere to accessibility standards.
Related to #https://github.com/TheOdinProject/odin-bot-v2/pull/403
Per comments on prior PR, there is currently no testing requirement for slash-commands. However, I have confirmed that the command works in a private Discord test server.
Original post with link to blog post: https://discord.com/channels/505093832157691914/564517555629457428/1146483003019767828 …
=> new-era-commands/slash: Add memory command

new-era-commands/slash/ai.js, new-era-commands/slash/bookmark.js, new-era-commands/slash/code.js, new-era-commands/slash/contribute.js, new-era-commands/slash/data.js, new-era-commands/slash/debug.js, new-era-commands/slash/freelance.js, new-era-commands/slash/notes.js, new-era-commands/slash/portfolio.js, new-era-commands/slash/question.js, new-era-commands/slash/top.js, new-era-commands/slash/windows.js
Allows a user to be tagged in a slash command without the need to send an additional message.
Will be particularly convenient once the full switch to slash commands (bar exceptions) is made.
- Added optional user mention to relevant slash commands, as per current `/google` and `/time` commands
Closes #404
N/A
-   [x] If this PR addresses an open …
=> Slash commands: Add optional user mention option

botCommands/__snapshots__/os.test.js.snap, botCommands/os.js, botCommands/os.test.js, new-era-commands/slash/os.js
**DO NOT MERGE:** Depends on TheOdinProject/curriculum/pull/25402
- Once we've moved to support WSL, its easier to disclaim that every OS not mentioned isn't supported, rather than trying to account for every possible edgecase (But what about TempleOS???)
- Adds a generic `!os` command which makes it clear that everything not mentioned as supported is unsupported
-   [x] The `This PR` section has a bullet point list describing the …
=> OS: Add generic OS command

new-era-commands/slash/tutorialHell.js
Benefit:
- Reduce friction to provide learners with what TOP recommends regarding topic
- Learners get consistent messaging.
Solves:
- Having to search for a pinned message, or taking the time to type out a response in the moment that paraphrases the advice contained in the pin.
- Less workload for those involved in moderating or even helping out in chat.
- creates /tutorialhell command
- optional user ping
- contains edited content discussed in issue
Closes #462 
- Summarized Briggs's messages on the topic, and added Carlos's message about picking a course and sticking with it, to be more directive for those who need that, and a bit more course agnostic. If someone feels that FCC or whatever is the best course for them, I am happy for them.
- I'm not in love with the numbering, but I …
=> Bot: create tutorialhell command

new-era-commands/slash/stuck.js
Using the attachment builder direct from the source files will be too costly. Statically is the standard method to use images in these repos.
- Replaces the `stuck.jpg` image via the AttachmentBuilder with a Statically CDN link
N/A
Relates to #497
Proof of testing:
-   [x] …
=> /stuck: Replace attachment builder with Statically link

services/update-faq/update-faq.service.js, services/update-faq/update-faq.service.test.js
- I was looking at this recently, and I wasn't entirely happy with how I wrote this
- changes the delimiter switch to a sensible default of prepend unless said otherwise
- changes the adding code to a ternary instead of an if, and in doing so removes the weird double negation I had going on
- updates tests to account for this
-   [x] If this PR …
=> Feat: Make Update FAQ segment logic more concise

botCommands/points.js, botCommands/points.test.js, events/message-create.js, package-lock.json, package.json, services/getting-hired-message.service.js, utils/is-admin.js, utils/is-admin.test.js
- We currently duplicate this code
- Adds an `isAdmin(member)` utility
- Replace all code that did this previously with usages of the new function
- Fixes using `Map()` for mocking in `points.test.js` to use `Collection()` instead
- Runs prettier over all affected files
Closes #566
<s>-   [] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`</s>
-   [x] If this PR addresses an open issue, it is linked in the …
=> Feat: Add is admin utility

botCommands/points.js
- Some parameters aren't used by `getUserIdsFromMessage()`
- Drops them
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
=> Chore: Points: Drop unused parameters from `getUserIdsFromMessage()`

.github/ISSUE_TEMPLATE/feature_request.yaml
- There is an extra ` in the template, which breaks the markdown formatting
- Removes it
=> Feature_request.yaml: Remove extra `

.github/workflows/prettier.yml
Since we have Prettier as a dependency with a `.prettierrc` file and `format` npm script, it'd help to have a pull request workflow that checks all changed files for formatting issues (which can be fixed with a simple `npm run format -- <paths to files>`.
Left at a `--check` only workflow so any formatting that may need to be done can go in a separate commit for easier reviewing. If a `--write` workflow would be preferable, let me know.
If merged, I'll update the repo wiki with formatting instructions.
- Adds a check-only Prettier GH workflow
Closes #560
Could not find a way to achieve this via CirclCI - could only find out how to get path filtering to allow an action to run on specific file change (and run `prettier --check .` on everything), rather than an action to only target changed …
=> Feature: Add prettier GH workflow (--check only)

.env.sample, config.js
- #582 
- Allows channel ID's to be overridden via `.env`
- Modifies `.env.sample` to include a note on this functionality 
Closes #582 
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to …
=> Feat: Allow overriding channel config via .env file

botCommands/__snapshots__/os.test.js.snap, botCommands/os.js, lib/commandsContent.js
The current `/os` command has "Windows" as a title - a carryover from when it used to be `/windows`? The embed text could also probably do with being explicit about what Linux distros we do support.
- Amends `/os` command title to be OS-agnostic
- Amends `/os` embed wording and link text label
- Removes the url property from `!os` command to be consistent with other commands (not really used anyway since it just makes the title a link, and the embed already contains that link)
- Updates `/os` snapshots
N/A
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update …
=> /os: Amend title and body wording

botCommands/club_40_gifs.json
I was inspired randomly to see if I could remember how to use Gifntext.com
adds a stupid club 40 gif to spicy things up. I might add more, higher quality gifs. 
Closes #XXXXX
-   [x] If …
=> feat: add new club 40 gif

botCommands/__snapshots__/question-legacy.test.js.snap, botCommands/question-legacy.js, lib/commandsContent.js
The current `question` commands (both legacy and slash) use a bare URL for the question-asking guide. Like other links in other existing embeds, a masked link would allow for an accessible link text label.
- Updates the `question` command embed content to use a masked link for the question-asking guide.
- Uses `lib/commandsContent.js` as `!question`'s source of truth.
- Updates `!question`'s snapshot.
N/A
-   [x] The `This PR` section …
=> !question: Use accessible link text label and unify contents with slash variant

new-era-commands/slash/stuck.js
We have a great community guide on [helping yourself before asking for help](https://www.theodinproject.com/guides/community/before_asking) that doesn't get used much. It's a great guide and would be very helpful in the `/stuck` command.
- Adds [helping yourself before asking for help](https://www.theodinproject.com/guides/community/before_asking) community guide link to `/stuck` embed contents.
N/A
-   [x] The `This PR` section has a …
=> /stuck: Add "before asking for help" community guide link

package.json
[By default, nodemon is unable to watch `.env` files](https://github.com/remy/nodemon/blob/master/faq.md#nodemon-doesnt-restart-on-env-change).
- Makes `dev` npm script watch `.env` changes on top of existing behaviour
N/A
Considered proposing removing nodemon in favour of native `node --watch` but nodemon is still superior for this workflow (watching required and relevant config files as well as `.env`) as `node --watch` only watches the dependency graph, and `node --watch-path` will just watch everything in a dir without further filtering, including `.md` changes).
=> Chore: Add .env to nodemon watch paths

.husky/pre-commit, package.json
The current installed Husky version is v9 but `package.json` contains the old v4 way of setting hooks. This doesn't work in v9 so `lint-staged` was never being run pre-commit. While we already have GH workflows for the same actions, it helps to have this at the local level too and reduce "appease linter/formatter" commits. Belts and braces.
- Migrates to husky v9 way of setting a pre-commit hook
- Adds `prepare` npm script to ensure `npm install` also initialises husky (its setup files include a `.gitignore` that ignores themselves) https://typicode.github.io/husky/how-to.html#manual-setup
- Amends `lint-staged` tasks for different file types to also include Prettier
N/A
Example trying to commit a single change to `index.js` that includes a `let foo;` somewhere.
Current behaviour:
With PR …
=> Fix: Migrate husky hooks to v9 format

bot-commands/context-menu/format-code.js, bot-commands/slash/opencollective.js, events/interaction-create.js, services/format-code/format-code.service.js, services/format-code/format-code.service.test.js, services/moderation-message-delete.service.js, services/opencollective/opencollective.service.js, services/spam-ban/__snapshots__/spam-banning.service.test.js.snap, services/spam-ban/spam-banning.service.js
Supplying "ephemeral" for interaction response options is deprecated. Utilize flags instead.
- All instances where "ephemeral" is used as an option are updated to use flags instead.
- importing MessageFlags class
- after changing all the instances , ran npm test -- -u (which changed "ephemeral": true to "flags": 64 in snapshots)
- all tests passes
> [!NOTE]
> i am on the ruby course and i don't know about jest and importing in js , so i could have made some obvious mistake...
Closes #692 
nil
=> chore: use flags for ephemeral messages
