TheOdinProject/odin-bot-v2

.env.sample

Add a sample file with environmental variables that are required for the bot to function properly.

Add .env.sample

---

botCommands/points.js

This changes the amount of users that display on the leader board so that Kevin, Briggs and Chad can be on the leader board. :tada:

Make more users display on the leaderboard

---

botCommands/simpleCommands.js

Adding a command with the forum link to find coding partner.

Add pairs command

---

botCommands/points.js

I'm not sure if it works. I was unable to test it, because if I paste this into a repl.it, other dependencies are not there, but it SHOULD work. Can you check?

Add start parameter to leaderboard function

---

botCommands/help.js
botCommands/points.js

Minor update so that start=10 actually starts at rank 10

Fix leaderboard start parameter

---

botCommands/partyParrot.js

http://cultofthepartyparrot.com/parrots/parrotdad.gif is broken.

Fix broken link

---

botEngine.js

/* will change if incorrect command */

Modified message listener for #rules to ignore non-loki members

---

botCommands/help.js

Prettier changed the double quotes.
Will fix, if changes do not work.

Added directed @mention to /code command

---

botEngine.js

Personalizes bot response to user and includes link back to the rules room.
Saying 'ok' clues in user they are incorrect about typing 'ok' and should return to the rules room.

add personalized response to i-didnt-read-the-rules

---

botEngine.js

Wording changes welcome. Didn't test it. Posts a message after each post, deletes itself after 12 hours

Creations message

---

botCommands/points.js

Because:
* We are hitting the limits before the end of each month with the free dyno.
This commit:
* Points the points bot commands to use endpoints on the web app.
* Removes the set points command as it is rarely used and doesn't fit with the new endpoint structure.

Chore: Move Points DB to the Web App

---

botCommands/simpleCommands.js

Removed Pairs from commands list.

---

botCommands/time.js

- Added /time command
- The grammar of the response differs if you mention 1, 2, or 3+ users.

Added time command

---

botCommands/mockData.js
botCommands/mockData.test.js
botCommands/mv.js

- Added a file for mock data
- Created mentions data for callbacks that expect mentions to be passed in and behave differently based on either, 0, 1, 2, or 3+ mentions
- Additionally, the mv command was pulled down from master
Sorry for the messy commits! I had to pull the new stuff from master and fix what branch I was on.

Added mock data file for mentions + fetch mv file from master

---

botEngine.js

updated role ID

---

botCommands/__snapshots__/callbacks.test.js.snap
botCommands/__snapshots__/carlosQuote.test.js.snap
botCommands/__snapshots__/help.test.js.snap
botCommands/__snapshots__/mv.test.js.snap
botCommands/__snapshots__/partyParrot.test.js.snap
botCommands/callbacks.test.js
botCommands/carlosQuote.test.js
botCommands/help.test.js
botCommands/helpers.js
botCommands/helpers.test.js
botCommands/mv.js
botCommands/mv.test.js
botCommands/partyParrot.js
botCommands/partyParrot.test.js

Tests were written for the following files:
callbacks.js
carlosQuote.js
help.js
mv.js
partyParrot.js

Add tests for multiple files

---

package-lock.json

Because:
* Heroku installs dev dependencies during the deploy.
This commit:
* Adds packages jest needs to the package-lock.json file.

Fix: Failing Heroku Deploy

---

README.md

- added instruction to install dependencies

add instructions to install dependencies

---

botCommands/__snapshots__/bootcamps.test.js.snap
botCommands/bootcamps.js
botCommands/bootcamps.test.js

- adds a bootcamp command with a "fun" message

add bootcamp command

---

botCommands/__snapshots__/debug.test.js.snap
botCommands/debug.js
botCommands/debug.test.js
botCommands/mockData.test.js

Add `/debug` command and fix one import error in `mockData.test.js`
#69

Add /debug command

---

botCommands/windows.js
botCommands/windows.test.js

I have wrapped a link in 'windows' command, so it disables the auto-embed. 
#101 is related with this pull request.

Modify 'windows' command to disable auto-embed

---

botCommands/__snapshots__/help.test.js.snap
botCommands/help.js
botCommands/help.test.js
package-lock.json

- [x ] You have read the [Odin Bot README/Contributing Guide](https://github.com/TheOdinProject/odin-bot-v2/blob/master/README.md).
Added a line suggesting the use of CodePen and Repl.it for larger code snippets.
#112

Added CodePen and Repl links to /code

---

botCommands/points.js

Points URL updated to use www. instead of naked domain. 
#XXXXX

update URL for points API to use www. domain

---

botCommands/__snapshots__/help.test.js.snap
botCommands/help.js

Added additional backtick because it was omitted in #123 
#XXXXX

add extra backtick and update snapshots for correct output

---

botCommands/points.js

The `awardPoints` command was being correctly fired off by our updated regex, and thus passed all tests, but internally  it was parsing the input with an outdated regex. This PR removes the obsolete regex and ensures that our mentions are processed with the correct regex. 
#122

remove obsolete regex and update regex used by awardPoints command

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js
botCommands/simpleCommands.test.js

I Created a /xy command and test to go with it under simpleCommands.js and simpleCommands.test.js. I already talked to @wise-king-sullyman in the discord under the bot playground text channel and he gave me the ok send my pr.
#128

Created /xy command and complimentary test

---

botEngine.js

adds an introductory message to #introduction-and-checkins channel in lieu of the new FAQ in discord.

feature: add introduction message to intro-and-checkins channel

---

botCommands/__snapshots__/top.test.js.snap
botCommands/top.js
botCommands/top.test.js

Added /top bot command that links to www.theodinproject.com
#XXXXX

/top bot command

---

botCommands/__snapshots__/faq.test.js.snap
botCommands/faq.js
botCommands/faq.test.js
botCommands/simpleCommands.test.js

Adds faq.js faq.test.js and fixes linting errors in simpleCommands.test.js
#132 #116

add /faq command.  Includes ESLint fixes

---

.circleci/config.yml
botCommands/simpleCommands.test.js
package.json

Because:
* It will allow us to ensure eslint is passing without having to pull down PR's locally.
This commit:
* Adds Eslint to the CI config.
* Adds a npm script for running Eslint.
We should be able to remove this step now we have both the tests and eslint in CI, if that's cool with you @twalton83?
#XXXXX

Chore: Add Eslint to Circle

---

botCommands/__snapshots__/help.test.js.snap
botCommands/help.js

This commit will update the `code` command to be in Rich Embed format of Discord
This PR is related to #137

Update code command to be in rich embed format

---

botCommands/__snapshots__/debug.test.js.snap
botCommands/debug.js
botCommands/debug.test.js

Message Embed Feature

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js

Only two files. I checked :')
Issue #146 
_Sorry about that_

Update question command to be in MessageEmbed

---

botCommands/__snapshots__/faq.test.js.snap
botCommands/faq.js

- [x ] You have read the [Odin Bot README/Contributing Guide](https://github.com/TheOdinProject/odin-bot-v2/blob/master/README.md).
Update the faq command to return a Discord MessageEmbed with a color, title, and description. Additionally, update the faq snapshot to reflect this change.
Closes #147

Update faq command to return a MessageEmbed

---

botCommands/__snapshots__/help.test.js.snap
botCommands/help.js

Fix mobile indentation for code command.
before:
after:
#XXXXX

Fix: mobile identation for code command

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js

Added missing double quote
#XXXXX

Fix: missing double quote on data command

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js

Changed the message in fg from `This is what you should've typed into Google` to `This query might help you find what you're looking for` to make it sound more neutral
Suggested on discord in contribution-suggestions

Change fg command  wording

---

botEngine.js

Added to the bot message posted in the "creations-showcase" channel which displays the message: "Reminder: This channel is for posting links to your creations only. You can discuss the projects posted here in the sibling channel creations-discussions" but with the change I have made, an extra sentence will be added to showcase the full message as 
"Reminder: This channel is for posting links to your creations only. You can discuss the projects posted here in the sibling channel <#634025871614803968> React to a project you've reviewed with :white_check_mark:. Try to review projects that haven't been reviewed yet!".
#XXXXX

Bot message encourages users to review projects

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js
botCommands/simpleCommands.test.js

Gandalf must be removed.
No issue linked.

Remove Gandalf Command

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js
botCommands/simpleCommands.test.js

There is no need for a cheeky LMGTFY and users are confused as to what FG means. This solves both problems.
#XXXXX

Change FG command to Google

---

botEngine.js
package-lock.json

This commit:
- adds exception handling (or rather, a try catch block to do nothing) to prevent the bot from crashing when the message's member is null

fix: exception handling for isAdminMessage

---

botCommands/__snapshots__/points.test.js.snap
botCommands/club_40_gifs.json
botCommands/points.js
botCommands/points.test.js

-   [X] I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
<hr>
**1. Because:** Sully manually posts hand crafted gifs for people who join Club-40 and needs to be pinged
Closes #196
**2. This PR:** Automates the process of posting a randomly …

Points command: Automatic Club-40 gif

---

index.js

This commit:
Updates the Guild ID to use the correct one for the Odin server

update guild id to use the Odin server id

---

botCommands/points.js
botEngine.js
constants/admin-roles.const.js

-   [x] I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
<hr>
- Moderators cannot add double points.
- Constants should be in a seperate directory.
- Creates a folder for constants
- Creates admin.roles.const.js …

Create a directory for constants and change instances of adminRoles with an import of adminRoles

---

botCommands/__snapshots__/partyParrot.test.js.snap
botCommands/partyParrot.js
botCommands/partyParrot.test.js

-   [X] I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
<hr>
**1. Because:** This command has a shark that isn't a parrot and could use more parrots
**2. This PR:** adds more parrots and removes the shark

PartyParrot command: Replace shark with new parrots

---

botCommands/__snapshots__/partyParrot.test.js.snap
botCommands/partyParrot.js
botCommands/partyParrot.test.js

-   [X] I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
<hr>
I came across new party parrot gifs. Thought they would fit well within the current collection of party parrots and add more variety. 
Closes #XXXXX
This …

partyParrot command: add partyparrot gifs

---

botCommands/__snapshots__/windows.test.js.snap
botCommands/windows.js

This commit:
- Updates the windows link to the appropriate, non-404 url

fix windows cmd link

---

botCommands/club_40_gifs.json

<hr>
I made a new club 40 gif
Adds a new club 40 gif to the bot

Add club 40 gif to the bot

---

botCommands/__snapshots__/debug.test.js.snap
botCommands/debug.js

This commit:
- Updates the ruby debug command link to the appropriate one.

update ruby debug link

---

.env.sample
botEngine.js
package-lock.json
package.json
services/getting-hired-message.service.js

This commit:
- Creates a service to direct message __or__ ping a user in `#getting-hired` if it is their first time "messaging" within the channel.
The user must:
- Have Redis installed and running on their local machine
- Provide a channel id to be used as the testing getting-hired channel in their local server  in the `.env`
- set the redis server id in their `.env` (the default address is currently present in the `.env.sample`)
TODO:
- Set heroku env variables
** Please make a PR against this feature branch for the message embed, will take care of everything else **

feat: getting hired message service

---

botEngine.js

Moves the instantiation of the client outside of the message listener

fix creation of redis connection on msg

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js

Change description of the simpleCommands.js question! command, and update the associated test
-   [x] I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
<hr>
After a conversation regarding the possibility of changing the question …

Question command: Update verbiage

---

config.js

attempt to stop the spamming of points in the voice-text channel

add voice-text to no-points channels

---

botEngine.js
index.js
services/bookmark-message.service.js

-   [X] I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date
<hr>
Bookmarking messages could come in handy.
Adds message bookmark feature to odin bot.
**Scenario**
-  User reacts to a message they wish to boomark with 🔖 …

Feature: bookmark messages

---

botEngine.js

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
<hr>
Closes #XXXXX

Wrap nobot query in try catch

---

botEngine.js
index.js
services/bookmark-message.service.js

<hr>
QOL change?
When user reacts with :x: to a Odin bot's DM, that message gets deleted.
n/a

Feat: allow users to delete Odin bot's messages in DM with a reaction

---

botCommands/__snapshots__/debug.test.js.snap
botCommands/__snapshots__/faq.test.js.snap
botCommands/__snapshots__/help.test.js.snap
botCommands/__snapshots__/leaderboard.test.js.snap
botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/__snapshots__/windows.test.js.snap
botCommands/debug.js
botCommands/faq.js
botCommands/help.js
botCommands/leaderboard.js
botCommands/simpleCommands.js
botCommands/windows.js
botEngine.js
index.js
package-lock.json
package.json
services/bookmark-message.service.js

<hr>
Latest versions
* Upgrade discord.js from v13 to v14
* Upgrade discord-api-types from v0.27.2 to 0.37.8
* Update all breaking API changes
* Update …

Chore: upgrade discord.js & discord-api-types

---

new-era-commands/slash/data.js
new-era-commands/slash/debug.js
new-era-commands/slash/help.js
new-era-commands/slash/question.js
new-era-commands/slash/top.js
new-era-commands/slash/windows.js

We should eventually utilize the newer slash APIs for applicable commands. This PR duplicates some of the word-based commands to slash commands so we can test them out.
List of commands that are duplicated:
* data
* debug
* help
* question
* top
* windows
Closes #XXXXX
-   [X] The `Because` section summarizes the reason for this PR
-   [X] The `This PR` section has a bullet point list describing the changes in this PR
-   [ ] If this PR addresses an open issue, it is linked in the `Issue` …

Feat: slash-ify some word-based commands to test drive them

---

new-era-commands/slash/searchtop.js

We occasionally need to search for prompts in TOP's website
Adds searchtop command
Closes #XXXXX
-   [ ] If applicable, I have ensured all tests related to any command files included in …

Add searchtop command

---

.github/ISSUE_TEMPLATE/feature_request.md

Switches from the curriculum issue naming convention to one more suited for this repository
- The current title naming that is suggested is taken straight from the curriculum, and doesn't fit this repository
- Updates it to one more suited to this repository, based on previous titles of issues
Closes #XXXXX
-   x ] The `Because` section summarizes the reason for this PR

Feature Request template: Update title naming conventions

---

botCommands/__snapshots__/help.test.js.snap
botCommands/help.js

- When I added the community expectation line I messed up the bolding, leading to a weird display (although apparently no one noticed)
- fixes that
See also https://github.com/TheOdinProject/odin-bot-v2/pull/252
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to …

Help command: fix bolding

---

new-era-commands/slash/chooseyourpath.js

Cool command I guess
Uses fate to decide what path user should pick
Closes #XXXXX
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, …

Add chooseyourpath command

---

botEngine.js

- There is still some code in BotEngine.js that isn't relevant with the current Discord setup, specifically messages meant to target #creations-showcase (the old channel, not the new forum). There is no point to this anymore, because we have fully switched to forums
- Removes code for automatically replying to any new messages in #creations-showcase 
-   [x] The `This PR` section has a bullet point list describing the changes in …

BotEngine.js: Remove legacy code from Botengine

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js
new-era-commands/slash/data.js

This is in line with the current `!question` command output. You can see them below each other [here in discord](https://discord.com/channels/505093832157691914/692909559442047098/1090025986617253918)
- change the required information style to bold in the `/data` command
- mirror these changes to the `!data` command so they're both in the new format
Closes #XXXXX
-   [x] The `This PR` section has a bullet point list describing the …

data slash command: add bold styling to the question template. & !data command to mirror these changes

---

package-lock.json
package.json

The bot is giving errors that might be fixed by updating
- update discord.js to v14.8
Closes #XXXXX
discord conversation with @01zulfi https://discord.com/channels/505093832157691914/692909559442047098/1091411608913317962
-   [ ] If this PR adds new features or …

update discord.js to 14.8

---

botCommands/points.js
botEngine.js
config.js
services/bookmark-message.service.js

* Improves QOL
* Put all guild related channel & role ids in config file
* Update breaking references
Closes #XXXXX
-   [X] The `Because` section summarizes the reason for this PR
-   [X] The `This PR` section has a bullet point list describing the changes in this PR
-   [X] If this PR addresses an open issue, it is linked in the `Issue` section
-   [X] If this PR adds new features or functionality, I have added new tests
-   [X] If applicable, I have ensured all tests related to any command …

Chore(QOL): Create channels & roles field in config file

---

botCommands/__snapshots__/simpleCommands.test.js.snap
botCommands/simpleCommands.js
new-era-commands/slash/question.js

- the current link in the !question and /question command is dead because the page has been moved
- updates it to point to the correct one
Closes #317
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all …

Question command: update question link

---

config.js
new-era-commands/slash/update-faq.js
services/update-faq/index.js
services/update-faq/update-faq.service.js
services/update-faq/update-faq.service.test.js

FAQs in #faq channel keep going out of sync with GitHub's version
Create a slash command which updates #faq with latest ones in our GitHub
Closes #XXXXX
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] If applicable, I have …

Feature: update faq service

---

config.js
events/message-create.js
events/ready.js
new-era-commands/slash/opencollective.js
new-era-commands/slash/support.js
services/getting-hired-message.service.js
services/opencollective/index.js
services/opencollective/opencollective.service.js
services/redis/index.js
services/redis/redis.service.js

we're going oc
`/support` && `/opencollective` commands
Closes #XXXXX
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots …

feat: /support && /opencollective

---

botCommands/__snapshots__/help.test.js.snap
botCommands/help.js

This embedded output has a blue left border colour. I changed it to "Odin Gold" as most outputs are. 
- changes the border color
- adjusts the snapshot for the test
Closes #XXXXX
-   [x] If …

update !code command output to odin gold coloured border

---

new-era-commands/slash/opencollective.js
new-era-commands/slash/support.js
services/opencollective/opencollective.service.js

https://github.com/TheOdinProject/odin-bot-v2/pull/363/
updates `/support` and `/opencollective`
Closes #XXXXX
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] If applicable, I have ensured all tests related to any command files …

chore: update /support && /opencollective

---

botCommands/__snapshots__/carlosQuote.test.js.snap
botCommands/carlosQuote.js

The current `!cqg` command looks very unformatted and messy. I also wanted to get some practice with the bot and thought this a good test case.
- use the Discord Embed Builder to reformat the command output
- format the quote itself into paragraphs for readability
Closes #XXXXX
Current:
Updated:
Another note about this command: It doesn't get used a lot. If we agree on a format for it, perhaps I can create a slash command as well. I can imagine slash commands getting used more because they show up as suggestions once a user enters `/`.
-   [x] The title of this PR follows the `location of change: brief description of change` format, e.g. …

update CQG command to output embed

---

botCommands/points.js

Update headers to include token in GET Reqeusts, related to: https://github.com/TheOdinProject/odin-bot-v2/issues/175
Closes #XXXXX
-   [x] If applicable, I have ensured all tests related to any …

Update authentication headers to include GET requests

---

new-era-commands/slash/contribute.js

I have created this command to give info to people about contributing to our repositories. 
- adds slash command `/contribute`
- outputs instructions on how to get started contributing to our repos
Closes #XXXXX
- our current slash commands don't 
-   [ ] If this PR adds …

Add a bot slash command: /contribute

---

botCommands/__snapshots__/carlosQuote.test.js.snap
botCommands/carlosQuote.js

The current render looks unformatted on mobile due to the indentation in the file:
- updates snapshot and test
- removes indentation and renders it like the below screenshot on mobile:
Closes #XXXXX
-   [x] If this PR adds new features or functionality, I have added new …

update !cqg command formatting to render correctly on mobile

---

new-era-commands/slash/pointinfo.js

The indentation causes the bot output to format incorrectly on small screens
- removes indentation so this command also formats nicely on small screens:
Before: 
After:
Closes #XXXXX
-   [ ] If …

/points command: fix syntax indentation to render correctly on smaller screens

---

new-era-commands/slash/freelance.js

- we're moving to slash commands
- adds the `/freelance` command
- 
Closes #XXXXX
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all …

add freelancing slash command

---

README.md

I believe all repos now link to the general contributing guide and there's already a bot wiki link in the readme file. 
- replaces second link to odin-bot-wiki to general contributing guide
Closes #XXXXX
-   [ ] If this PR adds new features or functionality, I have added …

Update README.md to include the general contributing guide

---

new-era-commands/slash/code.js

we are moving to slash commands. 
I also thought the bot output could use an update. If the feedback is positive on that change, I will also update the legacy `!code` command. That is one of the legacy commands we'll probably keep for being usable in a sentence. 
Current `!code` output:
This PR's updated `/code` output:
- adds `/code` command
- updates the output of the command replacing the 3 sections at the bottom with a list for readability
Closes #XXXXX
-   [x] The `Because` section summarizes …

add /code slash command with updated body

---

new-era-commands/slash/searchtop.js

- the embeds look nicer and stand out more from non-bot users
- this formats the link into a descriptive hyperlink
- add embed output
- change link into hyperlink with descriptive output including prompt
- add separate mention for the embed mention does not tag a person
Current bot output:
PR proposal:
PR with mention
Closes #XXXXX
-   [ ] If this PR …

update /searchtop slash command to contain embed and descriptive link

---

new-era-commands/slash/google.js

- we are moving to slash commands and there currently is none for the google command
- adds the `/google` slash command
- creates embed with descriptive link to Google results
- adds optional mention of the user outside the embed (for @'s inside an embed don't actually ping)
Preview of slash command:
Closes #XXXXX
-   [x] If this PR addresses an open …

add /google slash command with mention option

---

new-era-commands/slash/time.js

we are moving to slash commands. 
I have also updated the output to include a descriptive link. We can edit the original `!time` command for the time being if this one gets approved for consistency. Or we leave it be until we prune the old commands and make the move to slash official once all commands are updated.
- adds /time slash command.
- command has option to "ping" a specific user.
- command output is updated with a descriptive link instead of the old `!time` command output.
- command output is wrapped in an embed to clearly distinguish it from regular messages as a bot message.
Closes #XXXXX
-   [x] The title of this PR follows …

add /time slash command

---

new-era-commands/slash/top.js

It enhances the output of the bot command
- places the output of the /top slash command inside an embed
- changes the link to a descriptive hyperlink
- makes the slash description more specific
Closes #XXXXX
-   [ ] If this PR adds new features or functionality, I have …

update /top slash command to add descriptive link and embed

---

new-era-commands/slash/portfolio.js

A lot of people come to discord and receive advice about not spending too much time on certain projects. These are mostly projects never ending up on a resume. The article by @I3uckwheat linked in this bot command is one often used to inform learners about the projects that **are** worth the extra time and why. 
- adds /portfolio slash command
Closes #XXXXX
-   [x] The `This PR` section has a bullet point list describing the changes in …

add new /portfolio slash command

---

new-era-commands/slash/time.js

- Discord should be capitalised
- capitalise the word `Discord`
Closes #XXXXX
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all …

fix: capitalise the word Discord in the /time command

---

new-era-commands/slash/notes.js

we are moving to slash commands
- adds a `/notes` command
- updates the body of the command
- adds a descriptive link to the information
Closes #XXXXX
-   [ ] If applicable, I have ensured all …

add /notes slash command with updated body

---

botCommands/club_40_gifs.json

It should fix the bot being down 
- added comma to club-40 gif json file
https://discord.com/channels/505093832157691914/991035463949254767/1149355852613034024 
-   [ ] If applicable, I have …

OdinBot: club-40 gifs json - Add comma to fix broken json

---

botCommands/club_40_gifs.json

Requested by @ManonLef to be added to gif roster
- Adds a new club40 gif
N/A
As per [this Discord message](https://discord.com/channels/505093832157691914/514204569572605952/1152379258610651216) …

Club40: Add new welcome gif

---

botCommands/__snapshots__/top.test.js.snap
botCommands/top.js

I already had this one saved as an embed but apparently didn't commit it to the related PR. I'm not sure we want to keep this command once we start fully moving to slash commands so this will have low to no merge priority. If someone has time, it is worth a push for aesthetics I think. 
- changes `!top` command to an embed
- updates the contents to include a descriptive link
- mirrors the `/top` slash command output
- updates the snapshot for the test
Closes #XXXXX
related to: #390 
-   [x] The …

edit !top command to embed and update snapshot

---

new-era-commands/slash/ai.js
new-era-commands/slash/bookmark.js
new-era-commands/slash/code.js
new-era-commands/slash/contribute.js
new-era-commands/slash/data.js
new-era-commands/slash/debug.js
new-era-commands/slash/freelance.js
new-era-commands/slash/google.js
new-era-commands/slash/memory.js
new-era-commands/slash/notes.js
new-era-commands/slash/portfolio.js
new-era-commands/slash/question.js
new-era-commands/slash/searchtop.js
new-era-commands/slash/time.js
new-era-commands/slash/top.js
new-era-commands/slash/windows.js

- the user ping option had unnecessary code.
- removes `.?id` form the `getUser` interaction option
- removes `<@` and `>` around the `userId` reply since the user will now get pinged without them. 
Closes #XXXXX
-   [ ] If this PR adds new features or functionality, I …

Slash commands with user ping option: remove unneeded code de- and restructuring

---

new-era-commands/slash/research.js

We are converting to slash commands, this is the slash equivalent of the !cqg command.
I'm open to a different name. Since this command is about expecting doing your own research before asking, I've decided to go with `/research` for now.
- adds `/research` command including optional user ping that mirrors the text based `!cqg` command entirely
Closes #XXXXX
-   [x] The `This PR` section has a bullet point list describing the changes in …

cqg: add /research for the old !cqg / carlosquote command

---

new-era-commands/slash/bootcamps.js

We are converting to slash commands. 
- adds `/bootcamps` command including optional user ping
- updates the output of the command and includes an embed with descriptive link. 
Closes #XXXXX
- …

bootcamps: add updated bootcamps slash command

---

new-era-commands/slash/callbacks.js

We are converting to slash commands.
- adds `/callbacks` command including optional user ping
- updates the output of the command and includes an embed with descriptive link. 
Closes #XXXXX
-   [ …

callbacks: add updated bootcamps slash command

---

new-era-commands/slash/faq.js

We are converting to slash commands, this is the slash equivalent of the !faq command but with an updated text.
- adds `/faq` command including optional user ping
- edits the text output of the command compared to the !faq text-based one
- 
Closes #435 
-   [ ] If this PR …

faq: add /faq slash command with updated and embed body text

---

new-era-commands/slash/microverse.js

We are converting to slash commands. 
I'm not sure if mv is still misusing the content. We can dive into that later. We can always decide to remove this command but for the sake of moving fwd with the bot removal of text-based commands, I thought it simpler to convert this first. 
- adds `/microverse` command including optional user ping
- updates the output of the command and includes an embed with descriptive link. 
Closes #436
-   [x] …

mv: add /microverse slash command

---

new-era-commands/slash/bothelp.js

I would like to move forward with the final stages of the bot overhaul. This command will output information about how to see all slash commands at a glance, and maybe even more important (for learners in our discord that have been around longer); a list of which text based commands are still available, since I already see people using standalone text-based commands that have been removed. 
It would be great to also get some feedback on the remaining text-based commands, which would be:
`!xy`, `!code`, `!question`, `!google`, `!searchtop` and `!top`
If you approve of those, I can PR the complete the overhaul with removal of the remaining text based commands, old commands (like shrug, shurg, gush) and associated files. 
- add `/bothelp` command 
Closes #XXXXX
-   [x] I have thoroughly read …

/bothelp command added 

---

botCommands/__snapshots__/wsl.test.js.snap
botCommands/wsl.js
botCommands/wsl.test.js
new-era-commands/slash/wsl.js

**DO NOT MERGE:** Depends on TheOdinProject/curriculum/pull/25402
- We're moving to support WSL2
- Adds a new command to direct users to the wsl channel for support
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

WSL: Add WSL command

---

botCommands/__snapshots__/wsl.test.js.snap

- the bot command is broken, because I forgot to commit the updated snapshot
- updates the snapshot to account for the new channel ID
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to date

Fix WSL snapshot (oops)

---

Procfile

This reverts commit f61ef9944c785d09fb12c0aa40fc211f703c9c28.
Closes #XXXXX
-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
-   [ ] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all …

Revert "Update procfile"

---

new-era-commands/slash/tutorialHell.js

The quote type is mismatched between uses, and a comma is included inside quotes as opposed to outside by mistake.
- Unifies the type of quotes used
- Moves a comma inside one of the quotes to outside
N/A
Much love to Fred for the great command! \o/
-   [ ] If this PR adds …

/tutorialhell: Fix and unify punctuation

---

new-era-commands/slash/faq.js

- Improves `/faq` command's tone
- Change title to 'TOP FAQ'
- Remove quote about insanity
- Updated link to FAQ channel to use channel Id 
N/A
- https://discord.com/channels/505093832157691914/897162466226757692/1215373112032628736
-   [ ] If this PR adds new features or …

/faq - remove quote, update title, update link to channel id

---

new-era-commands/slash/stuck.js

The stuck diagram image has been improved.
- Updates the stuck command image with the new diagram image.
Closes #XXXXX
-   [x] If applicable, I have ensured all tests related to any command files …

Stuck command: Update the diagram image

---

package.json

- In #554 we added a `.prettierrc` but no option to run prettier via a npm script
- Adds a npm script (`format`) to run prettier

Feat: Package.json: Add format script

---

botCommands/__snapshots__/code-legacy.test.js.snap
botCommands/__snapshots__/top-legacy.test.js.snap
botCommands/code-legacy.js
botCommands/code-legacy.test.js
botCommands/os.js
botCommands/top-legacy.js
botCommands/wsl.js
botCommands/xy-legacy.js
commandsContent.js
config.js
events/message-reaction-add.js
lib/commandsContent.js
new-era-commands/slash/code.js
new-era-commands/slash/os.js
new-era-commands/slash/question.js
new-era-commands/slash/top.js
new-era-commands/slash/wsl.js
new-era-commands/slash/xy.js

- We duplicate a lot of command info
- Deduplicates all duplicated info to a single source of truth
- Updates the snapshots for two commands: both of these purely concern changing whitespace, and I've verified they do not affect the way the command actually looks
- Changes the way two commands declare name their variables to be consistent with the other files and avoid clashing names
Closes #553 
<details>
<summary>Before/After screenshots</summary>
Legacy commands
| Before | After |
| --- | --- |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/011994ce-dff8-44e5-85e5-cf4ede3bbb1c) | ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/c57ca15e-a0df-4952-afa9-fa286078b51b) |
| ![image](https://github.com/TheOdinProject/odin-bot-v2/assets/76259120/ …

Feat: Deduplicate command info

---

botCommands/__snapshots__/os.test.js.snap
lib/commandsContent.js

#547
- Updates the `os` description to link to the list of reasons TOP doesn't support Windows
- Updates the test snapshots
Closes #547
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to …

OS: Feat: Add list of reasons why TOP doesn't support Windows

---

new-era-commands/slash/help.js

- https://github.com/TheOdinProject/odin-bot-v2/pull/563#pullrequestreview-2222149252
- Escapes the backticks
Closes #XXXXX

/help: Fix: Escape Backticks

---

new-era-commands/slash/support.js

Updated donate emoji to '1270559118368964710' to be more 'open'
- Money bag emoji could be associated with 'greed' therefore the emoji was changed to the backer coin emoji to be more "open" 
- Updated money bag emoji to backer coin emoji.
- Updated `.setEmoji('💰');` to `.setEmoji('1270559118368964710')`.
Closes https://github.com/TheOdinProject/odin-bot-v2/issues/431 
- N/A
-   [x] The `This PR` section has a bullet point list describing …

/support: Fix: Update Emoji (#431)

---

events/message-reaction-add.js

It looks like a debug logging has found its way into the PR by accident. Was wondering why my terminal printing false every now and then.
removes a stray console.log()
Closes #XXXXX
-   [x] If …

Bug - Removes debug logging

---

new-era-commands/slash/ai.js

- Clarifies TOP's stance on asking for help with AI-generated code / Output
- Updated vocabulary to address the reason for the change, as well as cleaned up the existing command language. 
Closes #585 
-   [ ] If this PR adds new features or functionality, I have added new …

Odin Bot: '/ai' update verbiage

---

botCommands/club_40_gifs.json

One of the gifs looks to be expired from the website.
Closes #XXXXX
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are …

club_40_gifs.json: Remove expired club40 gif 

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- This is more syntactically correct
- This allows for introducing subheaders
- Converts the bold headings in ISSUE_TEMPLATES to markdown headers
- Runs prettier over them
(these should probably get converted to issue forms)
<del>-   [] The title of this PR follows the `location of change: brief description of change` format, e.g. `Callbacks command: Update verbiage`</del>

Chore: Use actual markdown headers

---

botCommands/points.js
botCommands/points.test.js

To limit abuse, our points system only allows gives points for a maximum of 5 mentions in a single message. Currently, the "you can only do 5 at a time..." message is sent even when only 5 mentions are made, which seems out of place. Ideally, it's only sent if 6+ mentions are included, so people know only 5 of them actually received points.
- Amends `points.js` to only send the 5-limit message if *more* than 5 mentions were included.
- Amends tests for this limit so they actually test when exceeding 5 points mentions in a single message. No snapshots needed to be updated.
- Formats `points.js` using our Prettier rule set.
N/A
-   [x] The …

Points: Send "5 limit message" only if exceeding 5 mentions

---

botCommands/club_40_gifs.json

More. *More.*
- Adds 4 new gifs to the club40 gif list
N/A
-   [x] If applicable, I have ensured all tests related to any command files included in this PR pass, and/or all snapshots are up to …

Club 40: Add new welcome gifs

---

new-era-commands/slash/college-students.js

Creates a slash command to help educate college students on TOP's stance on using our resources instead of their paid college resources.
- Creates / command `/college-students`
https://discord.com/channels/505093832157691914/1310777634589900831
-   [ ] If this PR adds new …

OdinBot:  /college-students command

---

services/moderation-message-delete.service.js

- Because bot would crash if mod tried to delete an automod message.
- Add support for deleting automod messages
- Handle empty message content
- Skip user notifications for system messages
- Add early return to ModMessageDeleteService to handle undeletable messages
Closes #XXXXX
Staff Announcement: https://discord.com/channels/505093832157691914/991035309422678046/1329454435692445791
-   [x] The `This PR` section has a bullet point list …

Bug(Odin-Bot): handle automod message deletion gracefully

---

botCommands/club_40_gifs.json

Random inspiration, perfect opportunity spotted :green_heart: 
- Adds new club 40 welcome gif
N/A
-   [x] If applicable, I have ensured all tests related to any command files included in this PR …

Club 40: Add new welcome gif

---

bot-commands/slash/imposter.js

Added a new slash command to help combat imposter-syndrome within our discord community.
- Added a slash command `/imposter` that will send out some encouraging statements regarding imposter-syndrome
- Includes a image that depicts the realities of imposter-syndrome.
Closes #640 
N/A

Feat: Added imposter-syndrome slash command

---

.github/ISSUE_TEMPLATE/feature_request.yaml

- GitHub is retiring the tasklist syntax and feature, and replacing it with sub tasks
- Drops the tasklist formatting from `feature_request.yaml`
Closes #673

Chore: Issue Templates: Drop Tasklist syntax from feature request template

---

index.js
utils/errors/duplicate-ids.js

- Having duplicated ID's can cause all sorts of weirdness
- Ensures all single channel ID's in `config.js` are set to a different value.
- Skips all ID's which are arrays
- throws an error if it finds duplicates
Closes #689

Feat: Ensure Channel ID's are unique

---

bot-commands/slash/bestpractice.js

Added the bot slash command /bestpractice linking to new TOP dev.to article.
Added bestpractice.js file containing the /bestpractice bot command.
Closes #711

bot-commands/slash/:Added bestpractice.js file for bestpractice command

---

bot-commands/slash/points.js
services/points/points.service.js

`/points info` was missed in #412 probably because the interaction handling was in a `services` file rather than the command file as with all the others. I don't think the other `/points` subcommands need the ping option - doesn't seem helpful.
- Allows `/points info` to include an optional user ping
N/A

/points info: Add optional user ping

---

events/message-create.js

I broke prod. Removed arg in https://github.com/TheOdinProject/odin-bot-v2/pull/732/commits/03358adf158170bf4a150ba614adbf8512729c87 but didn't realise it was needed for award-points.
N/A

award-points: Restore legacy command message argument
